#!/usr/bin/env bash

dot=$HOME/dotfiles

## Editor 
alias vi="nvim"
alias vim="nvim"

## zsh
alias zshconfig="vi ~/.zshrc"

## Common
alias mv="mv -i"
alias rm="rm -i"
alias cp="cp -i"
alias ls="lsd"
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
alias s="sudo systemctl"
alias j="journalctl -xe"
alias psg="ps aux | grep "
alias update="sudo apt update && sudo apt upgrade -y"


## Screen
alias 3screens="$dot/.screenlayout/3screens.sh"
alias mirrorscreen="$dot/.screenlayout/mirrorscreen.sh"
alias 2screens="$dot/.screenlayout/2screens1hor1ver.sh"
alias 4screens="$dot/.screenlayout/4screensNvidia.sh"

## Themes
alias theme="$dot/scripts/theme.sh -i"
alias theme1="$dot/scripts/theme.sh nord"
alias theme2="$dot/scripts/theme.sh gruvbox-dark"
alias theme3="$dot/scripts/theme.sh sbm"

## Sound
alias a2dp="pactl set-card-profile bluez_card.28_11_A5_DE_81_A4 a2dp_sink"
alias hsp="pactl set-card-profile bluez_card.28_11_A5_DE_81_A4 headset_head_unit"

## Butler Burton
alias bb="butler-burton"

## blaapi
alias blaapiprod="~/bjornlunden/scripts/testarblaapi.sh"

## ugrep
alias uq='ug -Q'
alias ux='ug -UX'
alias uz='ug -z'
alias grep='ugrep -G'
alias egrep='ugrep -E'
alias fgrep='ugrep -F'
alias pgrep='ugrep -P'
alias xgrep='ugrep -UX'
alias zgrep='ugrep -zG'
alias zegrep='ugrep -zE'
alias zfgrep='ugrep -zF'
alias zpgrep='ugrep -zP'
alias zxgrep='ugrep -zUX'
alias xdump='ugrep -X ""'

## Java
alias java8="source $dot/scripts/java/java8.sh"
alias java11="source $dot/scripts/java/java11.sh"
alias java13="source $dot/scripts/java/java13.sh"
alias java14="source $dot/scripts/java/java14.sh"

## random
alias matrix="cmatrix -C yellow"
alias cheat="cht.sh"
