# ___  ___  ___  ___  ___  ___  ___
#| -_||_ -|| . || .'||   ||_ -|| . |
#|___||___||  _||__,||_|_||___||___|
#          |_|
#___________________________________
backend: Inject
toggle_key: OFF
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
  - trigger: ":ipw"
    replace: "{{wireless}}"
    vars:
      - name: wireless
        type: shell
        params:
          cmd: "ifconfig | grep -1 wlp | grep inet | awk {'print $2'} | cut -d'/' -f1"
          
  - trigger: ":ipc"
    replace: "{{wired}}"
    vars:
      - name: wired
        type: shell
        params:
          cmd: "ifconfig | grep -1 enx | grep inet | awk {'print $2'} | cut -d'/' -f1"
  - trigger: ":path"
    replace: "{{path}}"
    vars:
      - name: path
        type: shell
        params:
          cmd: "echo $PATH"
  - trigger: ":uptime"
    replace: "{{uptime}}"
    vars:
      - name: uptime
        type: shell
        params:
          cmd: "uptime -p"
  - trigger: ":email"
    replace: "{{email}}"
    vars:
      - name: email
        type: shell
        params:
          cmd: curl -s https://api.fejk.it/v1/people\?amount\=1 | sed -n 's|.*"email":"\([^"]*\)".*|\1|p'
  - trigger: ":phone"
    replace: "{{phone}}"
    vars:
      - name: phone
        type: shell
        params:
          cmd: curl -s https://api.fejk.it/v1/people\?amount\=1 | sed -n 's|.*"phone":"\([^"]*\)".*|\1|p'
