#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "gruvbox"
    #colorscheme = "molokai"
    colorscheme = "badwolf"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Bootstrap autoload/myspacevim
    bootstrap_before = 'myspacevim#before'
    #bootstrap_after = 'myspacevim#after'
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    vimcompatible = true
    filemanager = "nerdtree"

[[custom_plugins]]
repo = "sjl/badwolf"
merged = 0

[[custom_plugins]]
name = 'vim-scripts/dbext.vim'
merged = 0

[[custom_plugins]]
name = 'metakirby5/codi.vim'
merged = 0

[[custom_plugins]]
name = 'pechorin/any-jump.vim'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"
  name = 'colorscheme'

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30
[[layers]]
  name = 'VersionControl'
[[layers]]
  name = 'git'
[[layers]]
  name = 'fzf'
[[layers]]
  name = 'debug'
[[layers]]
  name = 'lsp'

[[layers]]
  name = 'lang#go'
[[layers]]
  name = 'lang#javascript'
[[layers]]
  name = 'lang#json'
[[layers]]
  name = 'lang#typescript'
[[layers]]
  name = 'lang#dockerfile'
[[layers]]
  name = 'lang#html'
[[layers]]
  name = 'lang#python'
[[layers]]
  name = "lang#groovy"
[[layers]]
  name = "lang#java"
[[layers]]
  name = "lang#toml"
[[layers]]
  name = "lang#sh"
